# Generated by Django 2.0.6 on 2018-06-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='doc_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ID'),
        ),
    ]
