# Generated by Django 2.0.6 on 2018-06-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
